path: ../data/datasets
train:
  - Strawberry_Dataset_for_Object_Detection/train_aug/images

val:
  - Strawberry_Dataset_for_Object_Detection/val/images
  
test:
  - Strawberry_Dataset_for_Object_Detection/test/images

nc: 3
names: ['Grape', 'Tomato', 'Strawberry']
