path: ../data/datasets
train:
  - LaboroTomato_1/train_aug/images 
  - TomatoOD_1/train_aug/images

val:
  - LaboroTomato_1/val/images
  - TomatoOD_1/val/images

test:
  - LaboroTomato_1/test/images
  - TomatoOD_1/test/images

nc: 3
names: ['Grape', 'Tomato', 'Strawberry']
