path: ../data/datasets
train: 
  - Green_grapes/train_aug/images
  - Purple_grapes/train_aug/images

val: 
  - Green_grapes/val/images
  - Purple_grapes/val/images

test: 
  - Green_grapes/test/images
  - Purple_grapes/test/images

nc: 3
names: ['Grape', 'Tomato', 'Strawberry']
