path: ../data/datasets
train:
  - Cherry_Tomato_Dataset_1/train_aug/images
  - TomatoPlantfactoryDataset_1/train_aug/images

val:
  - Cherry_Tomato_Dataset_1/val/images
  - TomatoPlantfactoryDataset_1/val/images

test:
  - Cherry_Tomato_Dataset_1/test/images
  - TomatoPlantfactoryDataset_1/test/images

nc: 3
names: ['Grape', 'Tomato', 'Strawberry']
