path: ../data/datasets
train:
  - wgisd/train/images
  - Grapes_dataset/train/images

val:
  - wgisd/val/images
  - Grapes_dataset/val/images

test: 
  - wgisd/test/images
  - Grapes_dataset/test/images

nc: 3
names: ['Grape', 'Tomato', 'Strawberry']
